
var currencies = {
  USD: { name: "United States Dollar" },
  EUR: { name: "Euro" },
  KRW: { name: "South Korean Won" },
  JPY: { name: "Japanese Yen" },
  CNY: { name: "Chinese Yuan" },
  GBP: { name: "British Pound" },
  CAD: { name: "Canadian Dollar" },
  CHF: { name: "Swiss Franc" },
  SEK: { name: "Swedish Krona" },
  AUD: { name: "Australian Dollar" },
  HKD: { name: "Hong Kong Dollar" },
  TWD: { name: "Taiwan Dollar" },
  NZD: { name: "New Zealand Dollar" },
  ILS: { name: "Israeli New Sheqel" },
  DKK: { name: "Danish Krone" },
  NOK: { name: "Norwegian Krone" },
  SAR: { name: "Saudi Arabian Riyal" },
  KWD: { name: "Kuwaiti Dinar" },
  BHD: { name: "Bahraini Dinar" },
  AED: { name: "United Arab Emirates Dirham" },
  JOD: { name: "Jordanian Dinar" },
  EGP: { name: "Egyptian Pound" },
  THB: { name: "Thai Baht" },
  SGD: { name: "Singapore Dollar" },
  MYR: { name: "Malaysian Ringgit" },
  IDR: { name: "Indonesian Rupiah" },
  BND: { name: "Brunei Dollar" },
  INR: { name: "Indian Rupee" },
  PKR: { name: "Pakistani Rupee" },
  BDT: { name: "Bangladesh Taka" },
  PHP: { name: "Philippine Peso" },
  MXN: { name: "Mexican Peso" },
  BRL: { name: "Brazilian Real" },
  VND: { name: "Vietnam Dong" },
  ZAR: { name: "South African Rand" },
  RUB: { name: "Russian Rouble" },
  HUF: { name: "Hungarian Forint" },
  PLN: { name: "Polish Zloty" },

  AFN: { name: "Afghan Afghani" },
  ALL: { name: "Albanian Lek" },
  DZD: { name: "Algerian Dinar" },
  AOA: { name: "Angolan Kwanza" },
  ARS: { name: "Argentine Peso" },
  AMD: { name: "Armenian Dram" },
  AWG: { name: "Aruban florin" },
  AZN: { name: "Azerbaijani Manat" },
  BSD: { name: "Bahamian Dollar" },
  BBD: { name: "Barbados Dollar" },
  BYR: { name: "Belarus Ruble" },
  BZD: { name: "Belize Dollar" },
  BMD: { name: "Bermuda Dollar" },
  BTN: { name: "Bhutanese Ngultrum" },
  BOB: { name: "Bolivian Boliviano" },
  BAM: { name: "Bosnia and Herzegovina Mark" },
  BWP: { name: "Botswana Pula" },
  BGN: { name: "Bulgarian Lev" },
  BIF: { name: "Burundi Franc" },
  KHR: { name: "Cambodian Riel" },
  CVE: { name: "Cape Verde Escudo" },
  KYD: { name: "Cayman Islands Dollar" },
  XOF: { name: "CFA Franc BCEAO" },
  XAF: { name: "CFA Franc BEAC" },
  XPF: { name: "CFP Franc" },
  CLP: { name: "Chilean Peso" },
  COP: { name: "Colombian Peso" },
  KMF: { name: "Comoro Franc" },
  CDF: { name: "Congolese Franc" },
  XCP: { name: "Copper Pounds" },
  CRC: { name: "Costa Rica Colon" },
  HRK: { name: "Croatian Kuna" },
  CUP: { name: "Cuban Peso" },
  CZK: { name: "Czech Koruna" },
  DJF: { name: "Dijibouti Franc" },
  DOP: { name: "Dominican Peso" },
  XCD: { name: "East Caribbean Dollar" },
  SVC: { name: "El Salvador Colon" },
  ETB: { name: "Ethiopian Birr" },
  FKP: { name: "Falkland Islands Pound" },
  FJD: { name: "Fiji Dollar" },
  GMD: { name: "Gambian Dalasi" },
  GHS: { name: "Ghanaian Cedi" },
  GEL: { name: "Georgian Lari" },
  GIP: { name: "Gibraltar Pound" },
  XAU: { name: "Gold ounce" },
  GTQ: { name: "Guatemala Quetzal" },
  GNF: { name: "Guinean Franc" },
  GYD: { name: "Guyanese Dollar" },
  HTG: { name: "Haitian Gourde" },
  HNL: { name: "Honduras Lempira" },
  ISK: { name: "Iceland Krona" },
  IRR: { name: "Iranian Rial" },
  IQD: { name: "Iraqi Dinar" },
  JMD: { name: "Jamaican Dollar" },
  KZT: { name: "Kazakhstan Tenge" },
  KES: { name: "Kenyan Shilling" },
  KGS: { name: "Kyrgyzstani Som" },
  LAK: { name: "Lao Kip" },
  LVL: { name: "Latvian Lats" },
  LBP: { name: "Lebanese Pound" },
  LSL: { name: "Lesotho Loti" },
  LRD: { name: "Liberian Dollar" },
  LYD: { name: "Libyan Dinar" },
  LTL: { name: "Lithuanian Litas" },
  MOP: { name: "Macanese Pataca" },
  MKD: { name: "Macedonian Denar" },
  MGA: { name: "Malagasy Ariary" },
  MWK: { name: "Malawian Kwacha" },
  MVR: { name: "Maldives Rufiyaa" },
  MRO: { name: "Mauritania Ougulya" },
  MUR: { name: "Mauritius Rupee" },
  MDL: { name: "Moldovan Leu" },
  MNT: { name: "Mongolian Tugrik" },
  MAD: { name: "Moroccan Dirham" },
  MZN: { name: "Mozambican Metical" },
  MMK: { name: "Myanmar Kyat" },
  NAD: { name: "Namibian Dollar" },
  NPR: { name: "Nepalese Rupee" },
  ANG: { name: "Netherlands Antillean Guilder" },
  NIO: { name: "Nicaragua Cordoba" },
  NGN: { name: "Nigerian Naira" },
  KPW: { name: "North Korean Won" },
  OMR: { name: "Omani Rial" },
  PAB: { name: "Panamanian Balboa" },
  PGK: { name: "Papua New Guinea Kina" },
  PYG: { name: "Paraguayan Guarani" },
  PEN: { name: "Peruvian Nuevo Sol" },
  QAR: { name: "Qatar Rial" },
  RON: { name: "Romanian New Leu" },
  RWF: { name: "Rwanda Franc" },
  SHP: { name: "Saint Helena Pound" },
  WST: { name: "Samoan Tala" },
  STD: { name: "Sao Tome Dobra" },
  RSD: { name: "Serbian Dinar" },
  SCR: { name: "Seychelles Rupee" },
  SLL: { name: "Sierra Leonean Leone" },
  XAG: { name: "Silver Ounce" },
  SBD: { name: "Solomon Islands Dollar" },
  SOS: { name: "Somali Shilling" },
  LKR: { name: "Sri Lanka Rupee" },
  SDG: { name: "Sudanese Pound" },
  SRD: { name: "Surinamese Dollar" },
  SZL: { name: "Swaziland Lilageni" },
  SYP: { name: "Syrian Pound" },
  TJS: { name: "Tajikistani Somoni" },
  TZS: { name: "Tanzanian Shilling" },
  TTD: { name: "Trinidad and Tobago Dollar" },
  TND: { name: "Tunisian Dinar" },
  TRY: { name: "Turkish Lira" },
  TMT: { name: "Turkmenistani Manat" },
  UGX: { name: "Ugandan Shilling" },
  UAH: { name: "Ukraine Hryvnia" },
  UYU: { name: "Uruguayan New Peso" },
  UZS: { name: "Uzbekistan Som" },
  VUV: { name: "Vanuatu Vatu" },
  VEF: { name: "Venezuelan Bolívar Fuerte" },
  YER: { name: "Yemen Riyal" },
  ZMK: { name: "Zambian Kwacha" },
  ZWL: { name: "Zimbabwe Dollar" }
}
